spring:
  datasource:
#    url: jdbc:h2:file:./data/myDB
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
    url: jdbc:postgresql://localhost:5003/db-marketplace
    username: srv_mkp_open
    password: h5Omh9!HriU-b$7M
    driverClassName: org.postgresql.Driver
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8081
